POST http://localhost:3413/api/auth/register/email
Content-Type: application/json

{
  "email": "teste2@teste.com",
  "password": "teste"
}

###
POST http://localhost:3413/api/auth/register/phone
Content-Type: application/json

{
  "phoneNumber": "5521997712596"
}

###
POST http://localhost:3413/api/auth/login/phone
Content-Type: application/json

{
  "code": "5521995374929",
}

###

POST http://localhost:3413/api/auth/login/email
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "teste"
}

###
POST http://localhost:3413/api/auth/send-code/phone
Content-Type: application/json

{
  "phoneNumber": "5521995374929"
}

###
POST http://localhost:3413/api/auth/confirm-code/phone
Content-Type: application/json

{
  "phoneNumber": "5521995374929",
  "code": "39435"
}